"""
Building a Graph-Backed Reflection Mechanism for Agent Self-Improvement

This example demonstrates how to use RushDB's graph capabilities to build
an agent reflection system. The system records experiences, generates reflections,
analyzes patterns, and creates actionable insights for future decision-making.
"""

import os
from dotenv import load_dotenv
from rushdb import RushDB

load_dotenv()

# Initialize RushDB client
api_key = os.getenv("RUSHDB_API_KEY")
if not api_key:
    raise ValueError(
        "RUSHDB_API_KEY not found. "
        "Copy .env.example to .env and add your API key."
    )

db = RushDB(api_key)


def print_section(title):
    """Print a formatted section header."""
    print(f"\n{'=' * 50}")
    print(f" {title}")
    print(f"{'=' * 50}\n")


def print_step(number, message):
    """Print a formatted step message."""
    print(f"[{number}] {message}")


def create_experience_with_actions(session_id, session_type, topic, actions_data):
    """
    Create an experience record and attach actions to it.
    
    This demonstrates RushDB's relationship attachment feature.
    """
    experience = db.records.create(
        label="EXPERIENCE",
        data={
            "session_id": session_id,
            "type": session_type,
            "topic": topic,
            "status": "completed"
        }
    )
    
    for action_data in actions_data:
        action = db.records.create(label="ACTION", data=action_data)
        db.records.attach(
            source=experience,
            target=action,
            options={"type": "CONTAINS"}
        )
    
    return experience


def create_reflection_for_experience(experience, analysis_text, learnings):
    """
    Create a reflection record linked to an experience.
    
    This demonstrates how reflections are attached to experiences via
    the PRODUCES relationship.
    """
    reflection = db.records.create(
        label="REFLECTION",
        data={
            "analysis": analysis_text,
            "key_learnings": learnings,
            "timestamp": "2025-01-16T14:30:00Z"
        }
    )
    
    # Link the reflection to the experience
    db.records.attach(
        source=experience,
        target=reflection,
        options={"type": "PRODUCES"}
    )
    
    return reflection


def generate_insight_from_reflection(reflection, insight_data):
    """
    Generate an insight from a reflection and link them.
    
    Insights represent reusable lessons that can inform future actions.
    """
    insight = db.records.create(
        label="INSIGHT",
        data=insight_data
    )
    
    # Link insight to the reflection that generated it
    db.records.attach(
        source=reflection,
        target=insight,
        options={"type": "GENERATES"}
    )
    
    return insight


def find_insights_for_situation(situation_keywords):
    """
    Query the graph to find insights relevant to a given situation.
    
    This demonstrates graph traversal for pattern matching.
    """
    all_insights = db.records.find({
        "labels": ["INSIGHT"]
    })
    
    relevant_insights = []
    for insight in all_insights.data:
        applies_to = insight.get("applies_to", [])
        for keyword in situation_keywords:
            if keyword.lower() in [tag.lower() for tag in applies_to]:
                insight["_relevance_score"] = 0.9
                relevant_insights.append(insight)
                break
    
    return relevant_insights


def traverse_reflection_graph(experience_id):
    """
    Traverse the graph to find all insights related to an experience.
    
    Path: EXPERIENCE -> PRODUCES -> REFLECTION -> GENERATES -> INSIGHT
    """
    # Find the experience
    experience = db.records.find_by_id(experience_id)
    if not experience:
        return []
    
    # Find reflections produced by this experience
    reflections = db.records.find({
        "labels": ["REFLECTION"],
        "where": {
            "EXPERIENCE": {
                "$relation": {"type": "PRODUCES", "direction": "in"},
                "$id": experience_id
            }
        }
    })
    
    insights = []
    for reflection in reflections.data:
        # Find insights generated by each reflection
        generated_insights = db.records.find({
            "labels": ["INSIGHT"],
            "where": {
                "REFLECTION": {
                    "$relation": {"type": "GENERATES", "direction": "in"},
                    "$id": reflection["__id"]
                }
            }
        })
        insights.extend(generated_insights.data)
    
    return insights


def analyze_patterns_across_experiences():
    """
    Analyze patterns across multiple experiences to find common themes.
    
    This demonstrates higher-level graph analysis for pattern recognition.
    """
    # Find all experiences that had positive outcomes
    successful_experiences = db.records.find({
        "labels": ["EXPERIENCE"],
        "where": {"status": "completed"}
    })
    
    patterns = {
        "action_types": {},
        "topics": {},
        "total_experiences": len(successful_experiences.data)
    }
    
    for exp in successful_experiences.data:
        # Count action types
        actions = db.records.find({
            "labels": ["ACTION"],
            "where": {
                "EXPERIENCE": {
                    "$relation": {"type": "CONTAINS", "direction": "in"},
                    "$id": exp["__id"]
                }
            }
        })
        
        for action in actions.data:
            action_type = action.get("type", "unknown")
            patterns["action_types"][action_type] = \
                patterns["action_types"].get(action_type, 0) + 1
    
    return patterns


def main():
    print_section("Agent Reflection Mechanism Demo")
    
    # Step 1: Create new experiences with actions
    print_step(1, "Creating experiences and actions...")
    
    # Experience 1: Difficult customer interaction
    exp1 = create_experience_with_actions(
        session_id="support_101",
        session_type="customer_support",
        topic="billing_dispute",
        actions_data=[
            {"type": "greeting", "tone": "warm", "acknowledged_customer": True},
            {"type": "active_listening", "duration_seconds": 120},
            {"type": "empathy_expression", "phrase": "I understand your frustration"},
            {"type": "solution_proposal", "offered_discount": True},
            {"type": "resolution_confirmation", "customer_satisfied": True}
        ]
    )
    print(f'   ✓ Created experience: \'{exp1.data.get("session_id")}\'')
    
    # Experience 2: Technical troubleshooting
    exp2 = create_experience_with_actions(
        session_id="support_102",
        session_type="technical_support",
        topic="login_issue",
        actions_data=[
            {"type": "greeting", "tone": "professional"},
            {"type": "diagnostic_questions", "count": 5},
            {"type": "step_guide_provision", "steps": 4},
            {"type": "verification_check", "confirmed_working": True}
        ]
    )
    print(f'   ✓ Created experience: \'{exp2.data.get("session_id")}\'')
    
    print()
    
    # Step 2: Create reflections on experiences
    print_step(2, "Creating reflections on experiences...")
    
    refl1 = create_reflection_for_experience(
        experience=exp1,
        analysis_text=(
            "Customer was upset about unexpected charges. Starting with empathy "
            "and acknowledging their frustration before explaining the billing "
            "details helped calm the situation. Offering a small discount as "
            "compensation turned a negative interaction into a positive outcome."
        ),
        learnings=[
            "Empathy before solution reduces tension",
            "Acknowledge mistakes promptly",
            "Small gestures can salvage customer relationship",
            "Active listening is essential for understanding root issues"
        ]
    )
    print(f'   ✓ Created reflection for \'{exp1.data.get("session_id")}\'')
    
    refl2 = create_reflection_for_experience(
        experience=exp2,
        analysis_text=(
            "Customer couldn't log in due to forgotten password. Providing a "
            "clear step-by-step guide with numbered steps and confirming each "
            "stage worked well. The troubleshooting took longer than expected "
            "but the customer appreciated the structured approach."
        ),
        learnings=[
            "Step-by-step guides reduce confusion",
            "Confirm understanding at each step",
            "Technical issues require patience",
            "Clear communication prevents follow-up questions"
        ]
    )
    print(f'   ✓ Created reflection for \'{exp2.data.get("session_id")}\'')
    
    print()
    
    # Step 3: Generate insights from reflections
    print_step(3, "Generating insights from reflections...")
    
    insight1 = generate_insight_from_reflection(
        reflection=refl1,
        insight_data={
            "name": "empathy_first_approach",
            "description": (
                "When facing frustrated customers, lead with empathy before "
                "providing solutions. Acknowledge their feelings first."
            ),
            "applies_to": ["frustrated_customer", "billing_issue", "complaint"],
            "effectiveness_score": 0.94,
            "usage_count": 1
        }
    )
    print(f'   ✓ Generated insight: \'{insight1.data.get("name")}\'')
    
    insight2 = generate_insight_from_reflection(
        reflection=refl2,
        insight_data={
            "name": "structured_troubleshooting",
            "description": (
                "For technical issues, provide numbered steps and verify "
                "each stage before proceeding. This reduces confusion and "
                "prevents customer frustration."
            ),
            "applies_to": ["technical_issue", "login_problem", "configuration"],
            "effectiveness_score": 0.91,
            "usage_count": 1
        }
    )
    print(f'   ✓ Generated insight: \'{insight2.data.get("name")}\'')
    
    print()
    
    # Step 4: Find relevant insights for new situations
    print_step(4, "Finding insights for new situations...")
    print('   Query: "A frustrated customer with a billing question"\n')
    
    relevant_insights = find_insights_for_situation(
        situation_keywords=["frustrated_customer", "billing_issue"]
    )
    
    print(f'   Found {len(relevant_insights)} relevant insights:')
    for idx, insight in enumerate(relevant_insights, 1):
        print(f"   {idx}. {insight.get('name')} (confidence: {insight.get('effectiveness_score', 0):.2f})")
    
    print()
    
    # Step 5: Traverse the reflection graph
    print_step(5, "Traversing the reflection graph...")
    
    # Get insights for the first experience
    experience_insights = traverse_reflection_graph(exp1.id)
    
    print(f'   Experience \'{exp1.data.get("session_id")}\' produced insights:')
    for insight in experience_insights:
        print(f"   - {insight.get('name')}")
    
    if not experience_insights:
        print("   (No insights found - run seed.py first to populate data)")
    
    print()
    
    # Step 6: Analyze patterns across experiences
    print_step(6, "Analyzing patterns across experiences...")
    
    patterns = analyze_patterns_across_experiences()
    
    print(f"   Total experiences analyzed: {patterns['total_experiences']}")
    print("   Action type distribution:")
    for action_type, count in sorted(patterns["action_types"].items(), key=lambda x: -x[1]):
        print(f"   - {action_type}: {count} occurrences")
    
    # Find common pattern
    if patterns["action_types"]:
        most_common = max(patterns["action_types"].items(), key=lambda x: x[1])
        print(f"\n   Pattern found: '{most_common[0]}' appears most frequently")
    
    print()
    
    # Step 7: Demonstrate self-improvement loop
    print_step(7, "Demonstrating self-improvement loop...")
    
    # Create a new experience that incorporates past insights
    print('   Creating new experience informed by past insights...\n')
    
    # Get most effective insights
    all_insights = db.records.find({"labels": ["INSIGHT"]})
    if all_insights.data:
        top_insight = max(all_insights.data, key=lambda x: x.get("effectiveness_score", 0))
        print(f'   Using insight: "{top_insight.get("name")}"')
        print(f'   Description: {top_insight.get("description", "N/A")}')
        
        # Update usage count to simulate application
        updated_count = top_insight.get("usage_count", 0) + 1
        db.records.update(
            record_id=top_insight["__id"],
            data={"usage_count": updated_count}
        )
        print(f'   Updated usage count: {updated_count}')
    else:
        print("   (No insights in database - run seed.py to populate)")
    
    print()
    
    # Summary
    print_section("Summary")
    print("""
This example demonstrated:

1. EXPERIENCE creation with embedded ACTIONS
   - Actions are created and attached to experiences
   - Each action carries metadata about its effectiveness

2. REFLECTION generation from experiences
   - Reflections analyze what happened and extract learnings
   - Linked to experiences via the PRODUCES relationship

3. INSIGHT extraction from reflections
   - Insights are reusable lessons
   - Linked to reflections via the GENERATES relationship

4. Graph traversal for finding relevant insights
   - Query the graph based on situation context
   - Traverse EXPERIENCE -> REFLECTION -> INSIGHT paths

5. Pattern analysis across the graph
   - Find common action types and topics
   - Use patterns to guide future decision-making

The reflection loop: EXPERIENCE -> REFLECTION -> INSIGHT -> (improved) EXPERIENCE
""")
    
    print("Run 'python seed.py' to populate initial data, "
          "then 'python main.py' to see the system in action.\n")


if __name__ == "__main__":
    main()
