#!/usr/bin/env python3
"""
Seed script for Multi-Agent Collaborative Workflow hypergraph demo.

Creates a realistic multi-agent research collaboration scenario with:
- 5 AI agents with different roles
- 4 research projects  
- 12 tasks across projects
- 15+ artifacts generated by agents
- Hyperedge relationships showing collaboration patterns

Run this once before executing main.py. Safe to run multiple times (idempotent).
"""

import os
import sys
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Verify RushDB is available
try:
    from rushdb import RushDB
except ImportError:
    print("Error: rushdb package not installed. Run: pip install -r requirements.txt")
    sys.exit(1)


def clean_existing_data(db: RushDB) -> None:
    """Remove any previously seeded data for idempotent seeding."""
    labels_to_clean = ["ARTIFACT", "TASK", "PROJECT", "AGENT"]
    for label in labels_to_clean:
        db.records.delete_many({"labels": [label], "where": {}})
    print("  [0/5] Cleaned existing data...")


def create_agents(db: RushDB) -> list:
    """Create 5 AI agents with distinct roles."""
    print("  [1/5] Creating agents...")
    
    agents_data = [
        {
            "name": "Alice Chen",
            "role": "researcher",
            "capabilities": ["literature_review", "information_synthesis", "hypothesis_generation"],
            "specialization": "natural_language_processing"
        },
        {
            "name": "Bob Patel",
            "role": "architect",
            "capabilities": ["system_design", "performance_optimization", "scalability_planning"],
            "specialization": "distributed_systems"
        },
        {
            "name": "Carol Williams",
            "role": "reviewer",
            "capabilities": ["code_review", "quality_assurance", "bug_detection", "security_audit"],
            "specialization": "software_engineering"
        },
        {
            "name": "David Kim",
            "role": "coder",
            "capabilities": ["implementation", "testing", "debugging", "documentation"],
            "specialization": "machine_learning_systems"
        },
        {
            "name": "Emma Zhang",
            "role": "synthesizer",
            "capabilities": ["knowledge_synthesis", "report_writing", "presentation_design"],
            "specialization": "ai_interpretability"
        }
    ]
    
    agents = db.records.create_many(label="AGENT", data=agents_data)
    print(f"    Created {len(agents.data)} agents")
    return agents.data



def create_projects(db: RushDB) -> list:
    """Create 4 research projects."""
    print("  [2/5] Creating projects...")
    
    projects_data = [
        {
            "name": "Project Alpha: Semantic Search Engine",
            "description": "Build a production-ready semantic search system with sub-100ms latency",
            "priority": "high",
            "deadline": "2025-03-31"
        },
        {
            "name": "Project Beta: Context Compression Study",
            "description": "Research and implement novel context compression techniques for LLMs",
            "priority": "medium",
            "deadline": "2025-04-15"
        },
        {
            "name": "Project Gamma: Multi-Agent Orchestrator",
            "description": "Design a framework for orchestrating multiple specialized AI agents",
            "priority": "high",
            "deadline": "2025-05-01"
        },
        {
            "name": "Project Delta: Evaluation Framework",
            "description": "Create comprehensive benchmarks for evaluating AI agent collaborations",
            "priority": "low",
            "deadline": "2025-06-30"
        }
    ]
    
    projects = db.records.create_many(label="PROJECT", data=projects_data)
    print(f"    Created {len(projects.data)} projects")
    return projects.data


def create_tasks(db: RushDB, projects: list) -> list:
    """Create 12 tasks distributed across projects."""
    print("  [3/5] Creating tasks...")
    
    tasks_data = [
        # Project Alpha tasks
        {
            "title": "Research semantic search architectures",
            "description": "Survey existing approaches: dense, sparse, and hybrid retrieval",
            "priority": "high",
            "estimated_hours": 20,
            "PROJECT": {"name": "Project Alpha: Semantic Search Engine"}
        },
        {
            "title": "Implement semantic search algorithm",
            "description": "Build core semantic search functionality with embedding-based retrieval",
            "priority": "high",
            "estimated_hours": 40,
            "PROJECT": {"name": "Project Alpha: Semantic Search Engine"}
        },
        {
            "title": "Design system architecture",
            "description": "Create scalable architecture for semantic search service",
            "priority": "high",
            "estimated_hours": 15,
            "PROJECT": {"name": "Project Alpha: Semantic Search Engine"}
        },
        # Project Beta tasks
        {
            "title": "Literature review on context compression",
            "description": "Review recent papers on KV cache compression, retrieval, and summarization",
            "priority": "medium",
            "estimated_hours": 25,
            "PROJECT": {"name": "Project Beta: Context Compression Study"}
        },
        {
            "title": "Implement compression baseline",
            "description": "Build baseline implementation of existing compression techniques",
            "priority": "medium",
            "estimated_hours": 35,
            "PROJECT": {"name": "Project Beta: Context Compression Study"}
        },
        # Project Gamma tasks
        {
            "title": "Design agent communication protocols",
            "description": "Define message passing and state synchronization mechanisms",
            "priority": "high",
            "estimated_hours": 20,
            "PROJECT": {"name": "Project Gamma: Multi-Agent Orchestrator"}
        },
        {
            "title": "Implement multi-agent coordination",
            "description": "Build orchestrator that assigns tasks and manages agent lifecycle",
            "priority": "high",
            "estimated_hours": 50,
            "PROJECT": {"name": "Project Gamma: Multi-Agent Orchestrator"}
        },
        {
            "title": "Optimize embedding model",
            "description": "Fine-tune and optimize embedding models for agent communication",
            "priority": "medium",
            "estimated_hours": 30,
            "PROJECT": {"name": "Project Gamma: Multi-Agent Orchestrator"}
        },
        # Project Delta tasks
        {
            "title": "Define evaluation metrics",
            "description": "Establish benchmarks for collaboration quality, efficiency, and accuracy",
            "priority": "medium",
            "estimated_hours": 15,
            "PROJECT": {"name": "Project Delta: Evaluation Framework"}
        },
        {
            "title": "Build evaluation harness",
            "description": "Create automated testing framework for multi-agent workflows",
            "priority": "low",
            "estimated_hours": 40,
            "PROJECT": {"name": "Project Delta: Evaluation Framework"}
        },
        {
            "title": "Design visualization dashboard",
            "description": "Create UI for monitoring agent collaboration in real-time",
            "priority": "low",
            "estimated_hours": 25,
            "PROJECT": {"name": "Project Delta: Evaluation Framework"}
        },
        {
            "title": "Write comprehensive documentation",
            "description": "Document API, architecture, and usage patterns",
            "priority": "medium",
            "estimated_hours": 20,
            "PROJECT": {"name": "Project Delta: Evaluation Framework"}
        }
    ]
    
    tasks = db.records.create_many(label="TASK", data=tasks_data)
    print(f"    Created {len(tasks.data)} tasks")
    return tasks.data


def create_artifacts(db: RushDB, agents: list, projects: list) -> list:
    """Create 15+ artifacts generated by agents."""
    print("  [4/5] Creating artifacts...")
    
    artifacts_data = [
        # Research artifacts
        {
            "title": "Semantic search research summary",
            "type": "research_document",
            "format": "markdown",
            "AGENT": {"name": "Alice Chen"}
        },
        {
            "title": "Context compression literature review",
            "type": "research_document",
            "format": "markdown",
            "AGENT": {"name": "Alice Chen"}
        },
        {
            "title": "Agent communication protocol draft",
            "type": "design_document",
            "format": "markdown",
            "AGENT": {"name": "Bob Patel"}
        },
        # Implementation artifacts
        {
            "title": "Embedding implementation",
            "type": "code",
            "language": "python",
            "AGENT": {"name": "David Kim"}
        },
        {
            "title": "Search service implementation",
            "type": "code",
            "language": "python",
            "AGENT": {"name": "David Kim"}
        },
        {
            "title": "Orchestrator implementation",
            "type": "code",
            "language": "python",
            "AGENT": {"name": "David Kim"}
        },
        {
            "title": "Evaluation harness",
            "type": "code",
            "language": "python",
            "AGENT": {"name": "David Kim"}
        },
        # Architecture artifacts
        {
            "title": "System architecture diagram",
            "type": "diagram",
            "format": "svg",
            "AGENT": {"name": "Bob Patel"}
        },
        {
            "title": "Component interaction diagram",
            "type": "diagram",
            "format": "svg",
            "AGENT": {"name": "Bob Patel"}
        },
        # Review artifacts
        {
            "title": "Code review: semantic search",
            "type": "review",
            "status": "approved",
            "AGENT": {"name": "Carol Williams"}
        },
        {
            "title": "Code review: orchestrator",
            "type": "review",
            "status": "approved_with_suggestions",
            "AGENT": {"name": "Carol Williams"}
        },
        {
            "title": "Security review: search service",
            "type": "review",
            "status": "approved",
            "AGENT": {"name": "Carol Williams"}
        },
        # Synthesis artifacts
        {
            "title": "Final research synthesis",
            "type": "synthesis_document",
            "format": "markdown",
            "AGENT": {"name": "Emma Zhang"}
        },
        {
            "title": "Project Alpha status report",
            "type": "report",
            "format": "markdown",
            "AGENT": {"name": "Emma Zhang"}
        },
        {
            "title": "Evaluation framework summary",
            "type": "synthesis_document",
            "format": "markdown",
            "AGENT": {"name": "Emma Zhang"}
        },
        {
            "title": "Quarterly collaboration insights",
            "type": "report",
            "format": "markdown",
            "AGENT": {"name": "Emma Zhang"}
        }
    ]
    
    artifacts = db.records.create_many(label="ARTIFACT", data=artifacts_data)
    print(f"    Created {len(artifacts.data)} artifacts")
    return artifacts.data


def create_relationships(
    db: RushDB,
    agents: list,
    projects: list,
    tasks: list,
    artifacts: list
) -> None:
    """
    Create hyperedge relationships modeling multi-party collaboration.
    
    Key hypergraph patterns:
    - Tasks assigned to multiple agents (COLLABORATES_ON)
    - Agents contributing to multiple projects (WORKS_ON)
    - Tasks producing multiple artifacts (PRODUCES)
    - Projects containing multiple tasks (CONTAINS)
    - Agents reviewing multiple artifacts (REVIEWED_BY)
    """
    print("  [5/5] Creating collaboration relationships...")
    
    # Index records by name for easy lookup
    agents_by_name = {a["name"]: a for a in agents}
    projects_by_name = {p["name"]: p for p in projects}
    tasks_by_title = {t["title"]: t for t in tasks}
    artifacts_by_title = {a["title"]: a for a in artifacts}
    
    relationship_count = 0
    
    # TASK: 'Research semantic search architectures' - Alice only
    task = tasks_by_title["Research semantic search architectures"]
    agent = agents_by_name["Alice Chen"]
    db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
    relationship_count += 1
    
    # TASK: 'Implement semantic search algorithm' - Alice, David, Emma (hyperedge!)
    task = tasks_by_title["Implement semantic search algorithm"]
    for agent_name in ["Alice Chen", "David Kim", "Emma Zhang"]:
        agent = agents_by_name[agent_name]
        db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
        relationship_count += 1
    
    # TASK: 'Design system architecture' - Bob only
    task = tasks_by_title["Design system architecture"]
    agent = agents_by_name["Bob Patel"]
    db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
    relationship_count += 1
    
    # TASK: 'Literature review on context compression' - Alice only
    task = tasks_by_title["Literature review on context compression"]
    agent = agents_by_name["Alice Chen"]
    db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
    relationship_count += 1
    
    # TASK: 'Implement compression baseline' - David, Carol (hyperedge!)
    task = tasks_by_title["Implement compression baseline"]
    for agent_name in ["David Kim", "Carol Williams"]:
        agent = agents_by_name[agent_name]
        db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
        relationship_count += 1
    
    # TASK: 'Design agent communication protocols' - Bob, Alice (hyperedge!)
    task = tasks_by_title["Design agent communication protocols"]
    for agent_name in ["Bob Patel", "Alice Chen"]:
        agent = agents_by_name[agent_name]
        db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
        relationship_count += 1
    
    # TASK: 'Implement multi-agent coordination' - Bob, David (hyperedge!)
    task = tasks_by_title["Implement multi-agent coordination"]
    for agent_name in ["Bob Patel", "David Kim"]:
        agent = agents_by_name[agent_name]
        db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
        relationship_count += 1
    
    # TASK: 'Optimize embedding model' - Bob, David (hyperedge!)
    task = tasks_by_title["Optimize embedding model"]
    for agent_name in ["Bob Patel", "David Kim"]:
        agent = agents_by_name[agent_name]
        db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
        relationship_count += 1
    
    # TASK: 'Define evaluation metrics' - Emma, Carol (hyperedge!)
    task = tasks_by_title["Define evaluation metrics"]
    for agent_name in ["Emma Zhang", "Carol Williams"]:
        agent = agents_by_name[agent_name]
        db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
        relationship_count += 1
    
    # TASK: 'Build evaluation harness' - David, Carol (hyperedge!)
    task = tasks_by_title["Build evaluation harness"]
    for agent_name in ["David Kim", "Carol Williams"]:
        agent = agents_by_name[agent_name]
        db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
        relationship_count += 1
    
    # TASK: 'Design visualization dashboard' - Emma, Bob (hyperedge!)
    task = tasks_by_title["Design visualization dashboard"]
    for agent_name in ["Emma Zhang", "Bob Patel"]:
        agent = agents_by_name[agent_name]
        db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
        relationship_count += 1
    
    # TASK: 'Write comprehensive documentation' - Emma, Carol (hyperedge!)
    task = tasks_by_title["Write comprehensive documentation"]
    for agent_name in ["Emma Zhang", "Carol Williams"]:
        agent = agents_by_name[agent_name]
        db.records.attach(source=agent, target=task, options={"type": "COLLABORATES_ON", "direction": "out"})
        relationship_count += 1
    
    # WORK_ON relationships: Agents contributing to projects
    works_on_map = {
        "Alice Chen": ["Project Alpha: Semantic Search Engine", "Project Beta: Context Compression Study", "Project Gamma: Multi-Agent Orchestrator"],
        "Bob Patel": ["Project Alpha: Semantic Search Engine", "Project Gamma: Multi-Agent Orchestrator", "Project Delta: Evaluation Framework"],
        "Carol Williams": ["Project Beta: Context Compression Study", "Project Delta: Evaluation Framework"],
        "David Kim": ["Project Alpha: Semantic Search Engine", "Project Beta: Context Compression Study", "Project Gamma: Multi-Agent Orchestrator", "Project Delta: Evaluation Framework"],
        "Emma Zhang": ["Project Alpha: Semantic Search Engine", "Project Delta: Evaluation Framework"]
    }
    
    for agent_name, project_names in works_on_map.items():
        agent = agents_by_name[agent_name]
        for project_name in project_names:
            project = projects_by_name[project_name]
            db.records.attach(source=agent, target=project, options={"type": "WORKS_ON", "direction": "out"})
            relationship_count += 1
    
    # CONTAINS relationships: Projects containing tasks
    contains_map = {
        "Project Alpha: Semantic Search Engine": ["Research semantic search architectures", "Implement semantic search algorithm", "Design system architecture"],
        "Project Beta: Context Compression Study": ["Literature review on context compression", "Implement compression baseline"],
        "Project Gamma: Multi-Agent Orchestrator": ["Design agent communication protocols", "Implement multi-agent coordination", "Optimize embedding model"],
        "Project Delta: Evaluation Framework": ["Define evaluation metrics", "Build evaluation harness", "Design visualization dashboard", "Write comprehensive documentation"]
    }
    
    for project_name, task_titles in contains_map.items():
        project = projects_by_name[project_name]
        for task_title in task_titles:
            task = tasks_by_title[task_title]
            db.records.attach(source=project, target=task, options={"type": "CONTAINS", "direction": "out"})
            relationship_count += 1
    
    # PRODUCES relationships: Tasks producing artifacts
    produces_map = {
        "Research semantic search architectures": ["Semantic search research summary"],
        "Implement semantic search algorithm": ["Embedding implementation", "Search service implementation", "Code review: semantic search"],
        "Design system architecture": ["System architecture diagram"],
        "Literature review on context compression": ["Context compression literature review"],
        "Implement compression baseline": ["Code review: orchestrator"],
        "Design agent communication protocols": ["Agent communication protocol draft"],
        "Implement multi-agent coordination": ["Orchestrator implementation", "Code review: orchestrator", "Security review: search service"],
        "Optimize embedding model": ["Component interaction diagram"],
        "Define evaluation metrics": ["Evaluation framework summary"],
        "Build evaluation harness": ["Evaluation harness"],
        "Design visualization dashboard": ["Quarterly collaboration insights"],
        "Write comprehensive documentation": ["Project Alpha status report", "Final research synthesis"]
    }
    
    for task_title, artifact_titles in produces_map.items():
        task = tasks_by_title[task_title]
        for artifact_title in artifact_titles:
            artifact = artifacts_by_title[artifact_title]
            db.records.attach(source=task, target=artifact, options={"type": "PRODUCES", "direction": "out"})
            relationship_count += 1
    
    # CONTRIBUTED relationships: Agents contributing to artifacts
    contributed_map = {
        "Semantic search research summary": "Alice Chen",
        "Context compression literature review": "Alice Chen",
        "Agent communication protocol draft": "Bob Patel",
        "Embedding implementation": "David Kim",
        "Search service implementation": "David Kim",
        "Orchestrator implementation": "David Kim",
        "Evaluation harness": "David Kim",
        "System architecture diagram": "Bob Patel",
        "Component interaction diagram": "Bob Patel",
        "Code review: semantic search": "Carol Williams",
        "Code review: orchestrator": "Carol Williams",
        "Security review: search service": "Carol Williams",
        "Final research synthesis": "Emma Zhang",
        "Project Alpha status report": "Emma Zhang",
        "Evaluation framework summary": "Emma Zhang",
        "Quarterly collaboration insights": "Emma Zhang"
    }
    
    for artifact_title, agent_name in contributed_map.items():
        artifact = artifacts_by_title[artifact_title]
        agent = agents_by_name[agent_name]
        db.records.attach(source=agent, target=artifact, options={"type": "CONTRIBUTED", "direction": "out"})
        relationship_count += 1
    
    print(f"    Created {relationship_count} hyperedge relationships")


def main():
    """Main seeding function."""
    api_key = os.getenv("RUSHDB_API_KEY")
    if not api_key:
        print("Error: RUSHDB_API_KEY environment variable not set")
        print("Get your API key at https://app.rushdb.com")
        sys.exit(1)
    
    print("\nSeeding multi-agent collaborative workflow...")
    
    db = RushDB(api_key)
    
    # Clean existing data first for idempotency
    clean_existing_data(db)
    
    # Create all entities
    agents = create_agents(db)
    projects = create_projects(db)
    tasks = create_tasks(db, projects)
    artifacts = create_artifacts(db, agents, projects)
    
    # Create hyperedge relationships
    create_relationships(db, agents, projects, tasks, artifacts)
    
    print("\nSeeding complete!\n")


if __name__ == "__main__":
    main()
